# Seasonality - Gradle Properties

# Gradle JVM Settings
org.gradle.jvmargs = -Xmx1G
org.gradle.daemon = true
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.java.home=/usr/lib/jvm/temurin-25-jdk-amd64

# Source Options
# Use Modern Java(9+) Syntax (Courtesy of Jabel)
use_modern_java_syntax = false
# Convenient annotations for JVM-based languages
use_jetbrains_annotations = false

# Compilation Options

generate_sources_jar = true
generate_javadocs_jar = false


# Testing

enable_junit_testing = true
show_testing_output = false


# Mod Information (REQUIRED)
# HIGHLY RECOMMEND complying with SemVer: https://semver.org/

mod_version = 0.1.0-beta
root_package = com.oxnull.seasonality
mod_id = seasonality
mod_name = Seasonality


# Mod Metadata (Optional)

mod_description = Adds seasons similar to Serene Seasons but with some improvements, a complete code rewrite, some optimizations, and a few features: For example, the stars shine a little brighter in winter than in all the other seasons, or in summer the sun is brighter, and other things like snow recalculation. A few more features will be added in upcoming betas
mod_url = https://github.com/0xNull12/Seasonality
mod_update_json = 
mod_authors = 0xNull
mod_credits = Inspired by Serene Seasons by Glitchfiend Team
mod_logo_path = assets/seasonality/textures/gui/logo.png


# Mapping Properties

mapping_channel = stable
mapping_version = 39
use_dependency_at_files = true


# Run Configurations

minecraft_username = Developer
extra_jvm_args =
extra_tweak_classes =


# Maven Publishing
# Provide secrets: MAVEN_USER, MAVEN_PASS

publish_to_maven = false
publish_to_local_maven = false
maven_name = Seasonality
maven_url =


# Publishing (CurseForge / Modrinth)
# release_type can only be: release, beta or alpha

release_type = release
publish_with_changelog = ${{ it.file('CHANGELOG.md').exists() }}
client_side = true
server_side = true

# CurseForge (Provide secret: CURSEFORGE_TOKEN)
publish_to_curseforge = false
curseforge_project_id =
curseforge_debug = false

# Modrinth (Provide secret: MODRINTH_TOKEN)
publish_to_modrinth = false
modrinth_project_id =
modrinth_sync_readme = false
modrinth_debug = false


# Advanced Settings
# If any properties below change, refresh Gradle to apply


# Modify Minecraft Sources
change_minecraft_sources = false

# Tags (RetroFuturaGradle concept for build-time injection)
use_tags = true
tag_class_name = com.oxnull.seasonality.Tags

# Access Transformers
use_access_transformer = true
access_transformer_locations = seasonality_at.cfg

# Mixins
use_mixins = true
mixin_booter_version = 11.13
generate_mixins_json = false
mixin_configs = mixins.seasonality.json
mixin_connector_class =
mixin_refmap = mixins.seasonality.refmap.json
mixin_package = com.oxnull.seasonality.mixin

# Coremod
is_coremod = true
coremod_includes_mod = true
coremod_plugin_class_name = com.oxnull.seasonality.asm.SeasonalityLoadingPlugin

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5
